### ISSUE TITLE
THIS_IS_THE_SOURCE_CODE.txt not really up to date

### ISSUE THREAD

**Issue by ehx-v1** [Morlok8k/MinecraftLandGenerator#11]
The file THIS_IS_THE_SOURCE_CODE.txt doesn't really fit the current upload system. At the moment, the downloads are hosted in /zip/ inside the GitHub project, while the file tells there available at the download page. I was already aware of that, but some people might go to the download page and be like "wtf there's nothing here" and end up completely confused, so it would probably be a good idea to update that.

**Comment by Morlok8k** [comment]
fixed in commit e31eb92
