### ISSUE TITLE
MLG_Initial_Setup_Windows.cmd - Error in program arguments & The system cannot find the file specified.

### ISSUE THREAD

**Issue by Enkouyami** [Morlok8k/MinecraftLandGenerator#12]
During the setup I read that there was an error in program arguments and at the end, minecraft server wasn't launched.

Here's the output from MLG_Initial_Setup_Windows.cmd:
<details>
  <summary>Click to expand</summary>

>   Minecraft Land Generator - Initial Setup - Windows
>   C:\Users\Enko\MinecraftLandGenerator_1.7.6_Vanilla_Server\
>   [MLG] Minecraft Land Generator version 1.7.6
>   [MLG] BuildID: (1421666774000)
>   [MLG] This version was last modified on Monday, January 19, 2015 at 5:26 AM, Central Standard Time
>   [MLG]
>   [MLG] Uses a Minecraft server to generate square land of a specified size.
>   [MLG]
>   [MLG]
>   [MLG] Notice: Not waiting for anything...
>   [MLG] MLG-BuildID file downloaded.
>   [MLG] Archive Intergrity Check Passed. Offset: 7208sec.
>   [MLG-ERROR] Error in program arguments.
>   [MLG] Minecraft Land Generator version 1.7.6
>   [MLG] BuildID: (1421666774000)
>   [MLG] This version was last modified on Monday, January 19, 2015 at 5:26 AM, Central Standard Time
>   [MLG]
>   [MLG] Uses a Minecraft server to generate square land of a specified size.
>   [MLG]
>   [MLG]
>   [MLG] Notice: Not waiting for anything...
>   [MLG] _MLG_Readme.txt file created.
>   [MLG-ERROR] Error in program arguments.
>   [MLG] Minecraft Land Generator version 1.7.6
>   [MLG] BuildID: (1421666774000)
>   [MLG] This version was last modified on Monday, January 19, 2015 at 5:26 AM, Central Standard Time
>   [MLG]
>   [MLG] Uses a Minecraft server to generate square land of a specified size.
>   [MLG]
>   [MLG]
>   [MLG] Notice: Not waiting for anything...
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/MLG_Update_Files_Windows.txt
>   [MLG] Saving as: MLG_Update_Files_Windows.txt
>   [MLG] **
>   [MLG] 1369 byte(s) copied
>   [MLG] Elapsed Time: 1 Second
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/MLG_Update_Files.txt
>   [MLG] Saving as: MLG_Update_Files.txt
>   [MLG] ***
>   [MLG] 2928 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/Run_MLG_Windows.cmd
>   [MLG] Saving as: Run_MLG_Windows.cmd
>   [MLG] **
>   [MLG] 760 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/Run_Server_Windows.cmd
>   [MLG] Saving as: Run_Server_Windows.cmd
>   [MLG] **
>   [MLG] 865 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/Update_MLG_Windows.cmd
>   [MLG] Saving as: Update_MLG_Windows.cmd
>   [MLG] **
>   [MLG] 833 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/Update_Server_Windows.cmd
>   [MLG] Saving as: Update_Server_Windows.cmd
>   [MLG] **
>   [MLG] 863 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/Update_MLG_Extra_Files_Windows.cmd
>   [MLG] Saving as: Update_MLG_Extra_Files_Windows.cmd
>   [MLG] **
>   [MLG] 820 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/Update_MLG_Extra_Files_All-OS_Windows.cmd
>   [MLG] Saving as: Update_MLG_Extra_Files_All-OS_Windows.cmd
>   [MLG] **
>   [MLG] 819 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/MLG_Printspawn_Windows.cmd
>   [MLG] Saving as: MLG_Printspawn_Windows.cmd
>   [MLG] **
>   [MLG] 776 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/MLG_Initial_Setup_Linux.sh
>   [MLG] Saving as: MLG_Initial_Setup_Linux.sh
>   [MLG] **
>   [MLG] 1831 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/MLG_Initial_Setup_Mac.command
>   [MLG] Saving as: MLG_Initial_Setup_Mac.command
>   [MLG] **
>   [MLG] 1845 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/MLG_Initial_Setup_Windows.cmd
>   [MLG] Saving as: MLG_Initial_Setup_Windows.cmd
>   [MLG] **
>   [MLG] 1207 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/eula.txt
>   [MLG] Saving as: eula.txt
>   [MLG] **
>   [MLG] 11 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG] Downloading: https://raw.github.com/Morlok8k/MinecraftLandGenerator/master/scripts/server.properties
>   [MLG] Saving as: server.properties
>   [MLG] **
>   [MLG] 119 byte(s) copied
>   [MLG] Elapsed Time: 0 Seconds
>   [MLG] Done
>   [MLG-ERROR] Error in program arguments.
>   [MLG] Minecraft Land Generator version 1.7.6
>   [MLG] BuildID: (1421666774000)
>   [MLG] This version was last modified on Monday, January 19, 2015 at 5:26 AM, Central Standard Time
>   [MLG]
>   [MLG] Uses a Minecraft server to generate square land of a specified size.
>   [MLG]
>   [MLG]
>   [MLG] Notice: Not waiting for anything...
>   [MLG] Downloading: https://s3.amazonaws.com/MinecraftDownload/launcher/minecraft_server.jar
>   [MLG] Saving as: minecraft_server.jar
>   [MLG] *******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
>   [MLG] 2360903 byte(s) copied
>   [MLG] Elapsed Time: 2 Seconds
>   [MLG] Done
>   [MLG-ERROR] Error in program arguments.
>   [MLG] Minecraft Land Generator version 1.7.6
>   [MLG] BuildID: (1421666774000)
>   [MLG] This version was last modified on Monday, January 19, 2015 at 5:26 AM, Central Standard Time
>   [MLG]
>   [MLG] Uses a Minecraft server to generate square land of a specified size.
>   [MLG]
>   [MLG]
>   [MLG] Notice: Not waiting for anything...
>   [MLG] MinecraftLandGenerator.conf file created.
>   [MLG-ERROR] Error in program arguments.
>   [MLG] Minecraft Land Generator version 1.7.6
>   [MLG] BuildID: (1421666774000)
>   [MLG] This version was last modified on Monday, January 19, 2015 at 5:26 AM, Central Standard Time
>   [MLG]
>   [MLG] Uses a Minecraft server to generate square land of a specified size.
>   [MLG]
>   [MLG]
>   [MLG] Notice: Not waiting for anything...
>   [MLG] Notice: Warnings from Server are Ignored
>   [MLG-ERROR] The currently configured world does not exist! Launching the server once to create it...
>   [Server] Starting minecraft server version 1.5.2
>   Terminate batch job (Y/N)? n
>   The system cannot find the file specified.

</details>

**Comment by Morlok8k** [comment]
"[MLG-ERROR] Error in program arguments." can be safely ignored during initial setup - you should not see it when running normally.

As for "The system cannot find the file specified.", the setup script is looking to delete the temporary world just created.  But you pressed [CTL] + [C], which killed MLG, and it asked if you wanted to "Terminate batch job (Y/N)? n" which you said no to.  the next line in the script is deleting the world.

SO... all is working fine.
