### ISSUE TITLE
MLG fails to properly create world

### ISSUE THREAD

**Issue by Gallion** [Morlok8k/MinecraftLandGenerator#7]
MLG fails to properly launch the server to create the world when the world doesn't exist and instead tries to generate a null world.

**Comment by Morlok8k** [comment]
MLG does function correctly with the latest server (1.8.1).  its just on first launch if server.properties is missing it will say the world name is "null".  subsequent launches will show the correct name.

I'll review your changes.

**Comment by Morlok8k** [comment]
(FYI, i've added a eula.txt file that should allow MLG to run on new servers without the need for manual editing.)

**Comment by Gallion** [comment]
Right, it happens if you launch Run_MLG_XXX from a different working directory than the one it's in. I fixed it though so now it should work properly.
